# Package Overview
package_name: dog_vs_cat_model

# Variables
target: target

pipeline_name: dog_vs_cat_pipeline
pipeline_save_file: dog_vs_cat_model_output_v

train_dir: train
validation_dir: validation

DATASET_PATH: https://storage.googleapis.com/mledu-datasets/cats_and_dogs_filtered.zip

SELECTED_MODEL: MobileNetV2 # TODO use this config

# Model parameters
test_size: 0.20
random_state: 42
epochs: 10
batch_size: 20
learning_rate: 0.0001
